### ISSUE TITLE
Erroneous regions appearing (PT2019)

### ISSUE THREAD

**Issue by ghost** [zamaudio/ptf2ardour#15]
When running a test session we created I notice PTFormat is outputting extra regions that aren't in the project. 

The incorrect regions always appear to start immediately after a real region.

See below:

`Track_Name` t(0) r(1) @0
`Audio 1` t(1) r(1) @0
`Audio 1` t(1) r(2) @26500000 (Does not exist)
`Audio 2` t(2) r(1) @0
`Audio 2` t(3) r(1) @0
`Audio 3` t(4) r(2) @950000
`Audio 3` t(4) r(0) @2240000 (Does not exist)
`Audio 3` t(5) r(2) @950000
`Audio 3` t(5) r(1) @2240000 (Does not exist)

Any thoughts on why this might be happening?

Attached is the test session file & session info .txt.

[Regions.zip](https://github.com/zamaudio/ptformat/files/3383365/Regions.zip)

**Comment by zamaudio** [comment]
Thank you for reporting this!  And with your attached files I will be able to look into the issue soon.

**Comment by zamaudio** [comment]
@legareal fixed in 8d29d798
