### ISSUE TITLE
PT10 session - does not open

### ISSUE THREAD

**Issue by BenAtHarrison** [zamaudio/ptf2ardour#2]
ProTools session is attached.  User reports that the session is 96k, and was created in ProTools version 10.

When importing the file,  the dialog reports:
PT v10 Session @ 96000Hz
0 audio files
52 regions
40 active regions

... so apparently the audio files are not recognized in the "Audio Files" folder?

[Kopie von Hot Chilli Berlin Mix_2.zip](https://github.com/zamaudio/ptformat/files/930575/Kopie.von.Hot.Chilli.Berlin.Mix_2.zip)

**Comment by zamaudio** [comment]
Fixed in 3837aa5
