### ISSUE TITLE
File Paths

### ISSUE THREAD

**Issue by sounddroid** [zamaudio/ptf2ardour#6]
Awesome utility! Thank you.

Is there a way to print/store the file paths?

On a reverse, note, any way to write a new .ptx file and linking files to it? 

If you need any more test material, I can provide some.

**Comment by MarcSpecter** [comment]
Writing a ptx is much more complication because you to create valid data,
and the specification for that is pretty intricate (and closed).

**Comment by zamaudio** [comment]
The file paths should be by default in `./Audio Files/filename.wav` where the filenames are extracted already by ptftool.

**Comment by zamaudio** [comment]
I'm not taking on the challenge of writing a ptx generator, sorry, but feel free to send a PR.
