### ISSUE TITLE
Sample PTS file from ProTools 6 LE

### ISSUE THREAD

**Issue by kazeed** [zamaudio/ptf2ardour#7]
Hi,

This repo is amazing ! Thanks for the effort ! 

Sadly I'm trying to recover some sessions recorded like 14 years ago with Protools 5 / 6 LE and a digi001 interface that isn't compatible with anything modern anymore. Also sadly younger me was not keen enough to make an export to any other filetype when shutting down the old home studio.

I originally created this file back in 2004 and has not been opened since then.

It should be like:
- Version 6 (though some are still maybe 5 ? if so let me know and I'll upload a newer file, albeit more complex)
- Original Sample Rate: 44100 Hz
- Bitrate: 32 (at least the audio files seem to have this bitrate)
- Tracks: 4 mono (2 guitars, 2 voices if I recall correctly.
- Total audio files: 12 .wav + 1 .gkp file
- Total fade files: 1

[QADS_2003.zip](https://github.com/zamaudio/ptformat/files/2258788/QADS_2003.zip)

Hope it is of use to you,

Thanks!

**Comment by zamaudio** [comment]
Thanks for this, will look into it when I get time.

**Comment by zamaudio** [comment]
@kazeed fixed in 877fa281
